### ISSUE TITLE
Can i generate label.tsv?

### ISSUE THREAD

**Issue by brightbsit** [airsplay/py-bottom-up-attention#19]
## ❓ How to use Detectron2

Questions like:

I followed GETTING_STARTED.md. But it doesn't make a result file which include object's vector and label.

I want to get them. In this case, what can I do?

**Comment by yezhengli-Mr9** [comment]
Refers to [https://github.com/airsplay/py-bottom-up-attention/blob/834fa8b8123657fe6fa6b27c069015b824e07646/demo/detectron2_mscoco_proposal_maxnms.py#L54-L65](detectron2_mscoco_proposal_maxnms.py) suggested by various issues, including issue #6, etc.

**Comment by brightbsit** [comment]
@yezhengli-Mr9 I edit path but it happens.

`Config 'configs/VG-Detection/faster_rcnn_R_101_C4_caffemaxpool.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "demo/detectron2_mscoco_proposal_maxnms.py", line 259, in <module>
    detector = build_model()
  File "demo/detectron2_mscoco_proposal_maxnms.py", line 243, in build_model
    D2_ROOT, "configs/VG-Detection/faster_rcnn_R_101_C4_caffemaxpool.yaml"))
  File "/home/watermelon/anaconda3/envs/sibal/lib/python3.7/site-packages/detectron2/config/config.py", line 54, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/watermelon/anaconda3/envs/sibal/lib/python3.7/site-packages/fvcore/common/config.py", line 123, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/watermelon/anaconda3/envs/sibal/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/watermelon/anaconda3/envs/sibal/lib/python3.7/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/watermelon/anaconda3/envs/sibal/lib/python3.7/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.CAFFE_MAXPOOL'`

**Comment by yezhengli-Mr9** [comment]
I tried 5-6 configs but only succeed alongside this [demo/demo_feature_extraction_attr.ipynb](https://github.com/airsplay/py-bottom-up-attention/blob/master/demo/demo_feature_extraction_attr.ipynb).

**Comment by yezhengli-Mr9** [comment]
> ## ❓ How to use Detectron2
> Questions like:
> 
> I followed GETTING_STARTED.md. But it doesn't make a result file which include object's vector and label.
> 
> I want to get them. In this case, what can I do?

Actually, I have not investigated that we are talking about same `*.tsv`s. I just respond during leisure time. Please double check~

**Comment by yanchuqiao** [comment]
> @yezhengli-Mr9 I edit path but it happens.
> 
> ```
> `Config 'configs/VG-Detection/faster_rcnn_R_101_C4_caffemaxpool.yaml' has no VERSION. Assuming it to be compatible with latest v2.
> Traceback (most recent call last):
>   File "demo/detectron2_mscoco_proposal_maxnms.py", line 259, in <module>
>     detector = build_model()
>   File "demo/detectron2_mscoco_proposal_maxnms.py", line 243, in build_model
>     D2_ROOT, "configs/VG-Detection/faster_rcnn_R_101_C4_caffemaxpool.yaml"))
>   File "/home/watermelon/anaconda3/envs/sibal/lib/python3.7/site-packages/detectron2/config/config.py", line 54, in merge_from_file
>     self.merge_from_other_cfg(loaded_cfg)
>   File "/home/watermelon/anaconda3/envs/sibal/lib/python3.7/site-packages/fvcore/common/config.py", line 123, in merge_from_other_cfg
>     return super().merge_from_other_cfg(cfg_other)
>   File "/home/watermelon/anaconda3/envs/sibal/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
>     _merge_a_into_b(cfg_other, self, self, [])
>   File "/home/watermelon/anaconda3/envs/sibal/lib/python3.7/site-packages/yacs/config.py", line 478, in _merge_a_into_b
>     _merge_a_into_b(v, b[k], root, key_list + [k])
>   File "/home/watermelon/anaconda3/envs/sibal/lib/python3.7/site-packages/yacs/config.py", line 491, in _merge_a_into_b
>     raise KeyError("Non-existent config key: {}".format(full_key))
> KeyError: 'Non-existent config key: MODEL.CAFFE_MAXPOOL'`
> ```

Hi, can I ask how did you solve it. same happens for me
